Http/routes.php
<?php



Route::group(['middleware' => ['web']], function () {

	Route::group( array("prefix" => "admin", "as"=>"admin."), function() {

    	Route::group(['middleware' => 'auth:dcms'], function() {

    		//PRODUCTS
    		Route::group( array("prefix" => "products", "as"=>"products."), function() {

    			//CATEGORIES
    			Route::group( array("prefix" => "categories","as"=>"categories."), function() {
    				Route::get("{id}/copy", array("as"=>"{id}.copy", "uses" => "CategoryController@copy"));
    				Route::any("api/table", array("as"=>"api.table", "uses" => "CategoryController@getDatatable"));
    				Route::any("rebuildTree", array("as"=>"rebuildTree", "uses" => "CategoryController@rebuildTree"));
    			});
    			Route::resource("categories","CategoryController");

    			//INFORMATION
    			Route::group( array("prefix" => "information","as"=>"information."), function() {
    				Route::any("api/table", array("as"=>"api.table", "uses" => "InformationController@getDatatable"));
    				Route::any("api/articlerelationtable/{article_id?}", array("as"=>"api.articlerelationtable", "uses" => "InformationController@getArticleRelationTable"));
    				Route::any("api/plantrelationtable/{plant_id?}", array("as"=>"api.plantrelationtable", "uses" => "InformationController@getPlantRelationTable"));
    			});
    			Route::resource("information","InformationController");

    			//API
    			Route::group( array("prefix" => "api","as"=>"api."), function() {
    				Route::any("table", array("as"=>"table", "uses" => "ProductController@getDatatable"));
    				Route::any("tablerow", array("as"=>"tablerow", "uses" => "ProductController@getTableRow"));
    				Route::get("pim", array("as"=>"pim", "uses" => "ProductController@json"));
    				Route::get("xls", array("as"=>"xls", "uses" => "ProductController@json"));
    				Route::any("relation/table/{article_id?}", array("as"=>"relation.table", "uses" => "ProductController@getRelationDatatable"));
    			});
    			Route::get("{id}/copy/{country_id?}", array("as"=>"{id}.copy.{country_id}", "uses" => "ProductController@copy"));
    		});
    		Route::resource("products","ProductController");
    });
  });
});



 ?>

Http/Controllers/InformationController.php
<?php
namespace Dcms\Products\Http\Controllers;

use App\Http\Controllers\Controller;

use Dcms\Products\Models\Product;
use Dcms\Products\Models\Information;
use Dcms\Products\Models\Attachment;
use Dcms\Products\Models\Price;
use Dcms\Products\Models\Category;

use View;
use Input;
use Session;
use Validator;
use Redirect;
use DB;
use Datatables;
use Auth;

class InformationController extends Controller {

	public $informatationColumNames = array();
	public $informatationColumNamesDefaults = array(); // TO DO - the input on the information tab are array based
	public $productColumNames = array();
	public $productColumnNamesDefaults = array(); // e.g. checkboxes left blank will result in NULL database value, if this is not what you want, you can set e.g. array('checkbox_name'=>'0');
	public $extendgeneralTemplate = "";
	public $informationTemplate = "";

	public function __construct()
	{
		$this->informationColumNames = array( 'title'=>'information_name'
    											,'description_short'=>'information_description_short'
    											,'description'=>'information_description'
    											,'sort_id'=>'information_sort_id'
    											,'product_category_id'=>'information_category_id'
    											,'url_slug'=>'information_name'
    											,'url_path'=>'information_name'
    											);

		// this is custom DCM should be out of the vendor folder
		$this->informationColumNames = array_merge($this->informationColumNames,array(  ));
		// end of customisation

		$this->productColumNames = array('code'=>'code'
											,'eancode'=>'eancode'
											,'image'=>'image'
											,'volume'=>'volume'
											,'volume_unit_id'=>'volume_unit_id'
										);

		$this->extendgeneralTemplate = null;
		$this->informationTemplate = null;
	}


	/**
	 * get the data for DataTable JS plugin.
	 *
	 * @return Response
	 */
	public function getDatatable()
	{

		return Datatables::queryBuilder(	DB::connection("project")
													->table("products_information")
													->select(
																"products_information.id",
																"information_group_id",
																"title",
																(DB::connection("project")->raw("concat(\"<img src='/packages/dcms/core/images/flag-\", lcase(languages.country),\".png' > \") as regio"))
															)
													->leftJoin('languages','products_information.language_id', '=' , 'languages.id')
													->orderBy('information_group_id')
										)
			                        ->addColumn('edit', function($model){ return '<form method="POST" action="/admin/products/information/'.$model->id.'" accept-charset="UTF-8" class="pull-right"> <input name="_token" type="hidden" value="'.csrf_token().'"> <input name="_method" type="hidden" value="DELETE">
											<a class="btn btn-xs btn-default" href="/admin/products/information/'.(!is_null($model->information_group_id)?$model->information_group_id:"i-".$model->id).'/edit"><i class="fa fa-pencil"></i></a>

										</form>';})
			                        ->rawColumns(['regio','edit'])
			                        ->make(true) ;
	}


		/**
		 * get the data for DataTable JS plugin.
		 *
		 * @return Response
		 */
		public function getPlantRelationTable($plant_id = 0)
		{
						$query = DB::connection('project')
														->table('products_information as x')
														->select(
																(DB::connection("project")->raw('
																					information_group_id,
																					case when  locate(\'-SEP\',GROUP_CONCAT(title  order by  language_id SEPARATOR \'-SEP-\')) > 0 then substring(GROUP_CONCAT(title   order by  language_id SEPARATOR \'-SEP-\'), 1, (locate(\'-SEP\',GROUP_CONCAT(title  order by  language_id SEPARATOR \'-SEP-\')) - 1)) else title end as title,
																					case when (select count(*) from products_information_group_to_plants where products_information_group_to_plants.information_group_id = x.information_group_id and plant_id = "'.$plant_id.'") > 0 then 1 else 0 end as checked
																				')
															))
															->whereNotNull('x.information_group_id')
															->groupBy('x.information_group_id')
															->orderBy("language_id");

							return Datatables::queryBuilder($query)
											->addColumn('radio', function($model){return '<input type="checkbox" name="information_group_id[]" value="'.$model->information_group_id.'" '.($model->checked == 1?'checked="checked"':'').' id="chkbox_'.$model->information_group_id.'" > ';})
											->rawColumns(['radio'])
											->make(true);
		}


	/**
	 * get the data for DataTable JS plugin.
	 *
	 * @return Response
	 */
	public function getArticleRelationTable($article_id = 0)
	{

		$query = DB::connection('project')
										->table('products_information as x')
										->select(
												(DB::connection("project")->raw('
																	information_group_id,
																	case when  locate(\'-SEP\',GROUP_CONCAT(title  order by  language_id SEPARATOR \'-SEP-\')) > 0 then substring(GROUP_CONCAT(title   order by  language_id SEPARATOR \'-SEP-\'), 1, (locate(\'-SEP\',GROUP_CONCAT(title  order by  language_id SEPARATOR \'-SEP-\')) - 1)) else title end as title,
																	case when (select count(*) from articles_to_products_information_group where articles_to_products_information_group.information_group_id = x.information_group_id and article_id = "'.$article_id.'") > 0 then 1 else 0 end as checked
																')
											))
											->whereRaw('id IN (SELECT product_information_id FROM products_to_products_information WHERE product_id IN ( select id from products where online = 1 ) )')
											->whereNotNull('x.information_group_id')
											->groupBy('x.information_group_id')
											->orderBy("language_id");

		return Datatables::queryBuilder($query)
						   ->addColumn('radio', function($model){return '<input type="checkbox" name="information_group_id[]" value="'.$model->information_group_id.'" '.($model->checked == 1?'checked="checked"':'').' id="chkbox_'.$model->information_group_id.'" > '.$model->information_group_id;})

						   ->rawColumns(['radio'])
						   ->make(true) ;
	}


	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		return View::make('dcmsproducts::information/index');
	}

	/**
	 * return the requested json data.
	 *
	 * @return json data
	 */
	public function json()
	{
		$term = Input::get("term");
		$language_id = intval(Input::get("language"));
		//the json autoload tool needs some
		$pData = Information::select('id','title as label', 'description')->where('title','LIKE','%'.$term.'%')->where('language_id','=',$language_id)->get()->toJson();
		return $pData;
	}

	public function getCountriesLanguages($returnType = "array")
	{
		//RFC 3066
		$oCountriesLanguages = DB::connection("project")->select('SELECT id, country, language FROM languages ');

		if ($returnType === "model")
		{
			return $oCountriesLanguages;
		}
		else
		{
			$aCountryLanguage = array();
			if(!is_null($oCountriesLanguages) && count($oCountriesLanguages)>0)
			{
				foreach($oCountriesLanguages as $M)
				{
					$aCountryLanguage[$M->id] = strtolower($M->language)."-".strtoupper($M->country);
				}
			}
			return $aCountryLanguage;
		}
	}

	public function getCountries($returnType = "array")
	{
		$oCountries =  DB::connection("project")->select('SELECT id, country_name FROM countries');
		if ($returnType === "model") {
			return $oCountries;
		}
		else
		{
			$aCountries = array();
			foreach($oCountries as $c)
			{
				$aCountries[$c->id] = $c->country_name;
			}
			return $aCountries;
		}
	}


	//return the model to fill the form
	public function getExtendedModel()
	{
		//do nothing sit back and make the extension hook up.
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return "disabled - since there must be some volume on an information";
	}


	protected function validateProductForm()
	{
		// validate
		// read more on validation at http://laravel.com/docs/validation
		$rules = array(
			'code'       => 'required',
		);
		$validator = Validator::make(Input::all(), $rules);

		// process the login
		if ($validator->fails()) {
			return Redirect::back()//to('admin/products/' . $id . '/edit')
				->withErrors($validator)
				->withInput();
		} else {
			return true;
		}
	}

	/**
	 * Save the ProductInformation to the given product (object)
	 * this can be filtered by givin a single languageid - the filter helps for returning the model of the saved Information
	 * by default you get back the last saved Information object

	 * @return Product Object
	 */
	protected function saveProductInformation()
	{
		$input = Input::get();

		$pInformation = null; //pInformation = object product Information
		$aSavedInformationIDs = array();

		if (isset($input["information_language_id"]) && count($input["information_language_id"])>0)
		{
			foreach($input["information_language_id"] as $i => $language_id)
			{
				if ( (strlen(trim($input[$this->informationColumNames['title']][$i]))>0) )
				{
					$pInformation = null; //reset when in a loop
					$newInformation = true;
					if(intval($input["information_id"][$i]) > 0 )$pInformation = Information::find($input["information_id"][$i]);
					if(!isset($pInformation) || is_null($pInformation) ) $pInformation = new Information; else $newInformation = false;

					$oldSortID = null;
					if ($newInformation == false && !is_null($pInformation->sort_id) && intval($pInformation->sort_id)>0) $oldSortID = intval($pInformation->sort_id);

					foreach($this->informationColumNames as $column => $inputname)
					{
						if(isset($input[$inputname][$i])&&$column <> 'new' ) $pInformation->$column = $input[$inputname][$i];
						elseif(isset($input[$inputname][$i])&&$column == 'new' ) $pInformation->$column = intval($input[$inputname][$i]);
						elseif($column == 'new')$pInformation->$column = 0;

resources/views/information/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Products Information</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active"><i class="fa fa-shopping-cart"></i> Products</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">

                    @if (Session::has('message'))
                        <div class="alert alert-info">{!! Session::get('message') !!}</div>
                    @endif

                    <h2>Overview</h2>

                    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                        <tr>
                            <th>GroupID</th>
                            <th>Title</th>
                            <th>Regio</th>
                            <th>ID</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>

                    <script type="text/javascript">
                        $(document).ready(function () {
                            oTable = $('#datatable').DataTable({
                                "pageLength": 50,
                                "processing": true,
                                "serverSide": true,
                                "ajax": "{{ route('admin.products.information.api.table') }}",
                                "columns": [
                                    {data: 'id', name: 'ID'},
                                    {data: 'title', name: 'title'},
                                    {data: 'regio', name: 'regio', searchable: false},
                                    {data: 'id', name: 'id'},
                                    {data: 'edit', name: 'edit', orderable: false, searchable: false}
                                ]
                            });
                        });
                    </script>

                    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

                    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
                    <script type="text/javascript" language="javascript"
                            src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>


                    <script type="text/javascript">
                        $(document).ready(function () {

                            $(document).on("click", ".delete", function (e) {
                                bootbox.confirm("Are you sure?", function (result) {
                                    Example.show("Confirm result: " + result);
                                });
                            });

                        });
                    </script>

                    <script type="text/javascript" src="{!! asset('packages/dcms/core/assets/js/bootstrap.min.js') !!}"></script>
                    <script type="text/javascript" src="{!! asset('packages/dcms/core/assets/js/bootbox.min.js') !!}"></script>

                </div>
            </div>
        </div>
    </div>

@stop